runtime: python27
api_version: 1
threadsafe: false

instance_class: F2
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 5
  max_instances: 100
  min_pending_latency: 30ms  # default value
  max_pending_latency: automatic
  max_concurrent_requests: 50

env_variables:
        SENDGRID_API_KEY: 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
        # DJANGO_SETTINGS_MODULE: 'TrackingSystem.settings'
        # DATABASE_URL: 'mysql://root:GodBlessWuhan@host:godblesswuhan/TrackingSystem'


handlers:
        - url: /.*
          secure: always
          redirect_http_response_code: 301 
          script: TrackingSystem.wsgi.application
        - url: /static
          static_dir: static

libraries:
        - name: django
          version: "1.11"

        

        - name: MySQLdb
          version: "latest"
        
        