# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-05-01 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KumoGT', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='annual_review_doc',
            name='appr_cs_date',
            field=models.DateField(blank=True, null=True, verbose_name=b'Aprroved CS'),
        ),
        migrations.AddField(
            model_name='annual_review_doc',
            name='appr_ogs_date',
            field=models.DateField(blank=True, null=True, verbose_name=b'Aprroved OGS'),
        ),
        migrations.AddField(
            model_name='deg_plan_doc',
            name='appr_cs_date',
            field=models.DateField(blank=True, null=True, verbose_name=b'Aprroved CS'),
        ),
        migrations.AddField(
            model_name='deg_plan_doc',
            name='appr_ogs_date',
            field=models.DateField(blank=True, null=True, verbose_name=b'Aprroved OGS'),
        ),
        migrations.AddField(
            model_name='fin_exam_doc',
            name='appr_cs_date',
            field=models.DateField(blank=True, null=True, verbose_name=b'Aprroved CS'),
        ),
        migrations.AddField(
            model_name='fin_exam_doc',
            name='appr_ogs_date',
            field=models.DateField(blank=True, null=True, verbose_name=b'Aprroved OGS'),
        ),
        migrations.AddField(
            model_name='other_doc',
            name='appr_cs_date',
            field=models.DateField(blank=True, null=True, verbose_name=b'Aprroved CS'),
        ),
        migrations.AddField(
            model_name='other_doc',
            name='appr_ogs_date',
            field=models.DateField(blank=True, null=True, verbose_name=b'Aprroved OGS'),
        ),
        migrations.AddField(
            model_name='pre_exam_doc',
            name='appr_cs_date',
            field=models.DateField(blank=True, null=True, verbose_name=b'Aprroved CS'),
        ),
        migrations.AddField(
            model_name='pre_exam_doc',
            name='appr_ogs_date',
            field=models.DateField(blank=True, null=True, verbose_name=b'Aprroved OGS'),
        ),
        migrations.AddField(
            model_name='qual_exam_doc',
            name='appr_cs_date',
            field=models.DateField(blank=True, null=True, verbose_name=b'Aprroved CS'),
        ),
        migrations.AddField(
            model_name='qual_exam_doc',
            name='appr_ogs_date',
            field=models.DateField(blank=True, null=True, verbose_name=b'Aprroved OGS'),
        ),
        migrations.AddField(
            model_name='t_d_doc',
            name='appr_cs_date',
            field=models.DateField(blank=True, null=True, verbose_name=b'Aprroved CS'),
        ),
        migrations.AddField(
            model_name='t_d_doc',
            name='appr_ogs_date',
            field=models.DateField(blank=True, null=True, verbose_name=b'Aprroved OGS'),
        ),
        migrations.AddField(
            model_name='t_d_prop_doc',
            name='appr_cs_date',
            field=models.DateField(blank=True, null=True, verbose_name=b'Aprroved CS'),
        ),
        migrations.AddField(
            model_name='t_d_prop_doc',
            name='appr_ogs_date',
            field=models.DateField(blank=True, null=True, verbose_name=b'Aprroved OGS'),
        ),
    ]
