# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-05-01 18:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KumoGT', '0002_auto_20200501_1258'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deg_plan_doc',
            old_name='stu',
            new_name='stu1',
        ),
        migrations.RemoveField(
            model_name='annual_review_doc',
            name='appr_cs_date',
        ),
        migrations.RemoveField(
            model_name='annual_review_doc',
            name='appr_ogs_date',
        ),
        migrations.RemoveField(
            model_name='deg_plan_doc',
            name='appr_cs_date',
        ),
        migrations.RemoveField(
            model_name='deg_plan_doc',
            name='appr_ogs_date',
        ),
        migrations.RemoveField(
            model_name='fin_exam_doc',
            name='appr_cs_date',
        ),
        migrations.RemoveField(
            model_name='fin_exam_doc',
            name='appr_ogs_date',
        ),
        migrations.RemoveField(
            model_name='other_doc',
            name='appr_cs_date',
        ),
        migrations.RemoveField(
            model_name='other_doc',
            name='appr_ogs_date',
        ),
        migrations.RemoveField(
            model_name='pre_exam_doc',
            name='appr_cs_date',
        ),
        migrations.RemoveField(
            model_name='pre_exam_doc',
            name='appr_ogs_date',
        ),
        migrations.RemoveField(
            model_name='qual_exam_doc',
            name='appr_cs_date',
        ),
        migrations.RemoveField(
            model_name='qual_exam_doc',
            name='appr_ogs_date',
        ),
        migrations.RemoveField(
            model_name='t_d_doc',
            name='appr_cs_date',
        ),
        migrations.RemoveField(
            model_name='t_d_doc',
            name='appr_ogs_date',
        ),
        migrations.RemoveField(
            model_name='t_d_prop_doc',
            name='appr_cs_date',
        ),
        migrations.RemoveField(
            model_name='t_d_prop_doc',
            name='appr_ogs_date',
        ),
    ]
