# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-05-01 18:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KumoGT', '0003_auto_20200501_1300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deg_plan_doc',
            old_name='stu1',
            new_name='stu',
        ),
    ]
