# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-05-01 18:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KumoGT', '0004_auto_20200501_1305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deg_plan_doc',
            name='stu',
        ),
    ]
