# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-05-02 04:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KumoGT', '0005_remove_deg_plan_doc_stu'),
    ]

    operations = [
        migrations.AddField(
            model_name='deg_plan_doc',
            name='stu',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='deg_plan_docs', to='KumoGT.Student', verbose_name=b'Student'),
            preserve_default=False,
        ),
    ]
